# Dependencies
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]

highlighter: true

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
exclude:          [".gitignore", ".ruby-version", "CNAME", "LICENSE", "README.md", "Gemfile", "Gemfile.lock"]
port:             9001

url: https://dronebase.com
repo: https://github.com/dronebase/dronebase.github.io
